apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-role-binding-flink-all
subjects:
  - kind: ServiceAccount
    name: flink-service-account
roleRef:
  kind: ClusterRole
  name: flink-role
  apiGroup: rbac.authorization.k8s.io
